### ISSUE TITLE
Refactor for better experience

### ISSUE THREAD

**Issue by wen-templari** [nbtca/Sunday#51]
# Refactor Sunday

## Objective

+ Align design token with Hawaii.
+ Better experience on desktop side.
+ More robust.

## Timeline

TBD

## Tasks

```[tasklist]
### Tasks
- [ ] https://github.com/nbtca/Sunday/issues/52
- [ ] https://github.com/nbtca/Sunday/issues/57
- [ ] https://github.com/nbtca/Sunday/issues/59
- [x] Make logto as the only login method
- [x] Explore available notification methods
```
